#!/usr/bin/perl -w

use HAL;

use UniLang::Agent::Agent;
use UniLang::Util::Message;

$UNIVERSAL::agent = UniLang::Agent::Agent->new
  (Name => "HAL-9000",
   ReceiveHandler => \&Receive);
$UNIVERSAL::hal = HAL->new();

sub Receive {
  my %args = @_;
  $UNIVERSAL::hal->ProcessMessage
    (Message => $args{Message});
}

$UNIVERSAL::hal->Execute();
